# Generated by Django 4.2 on 2023-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.CharField(max_length=900),
        ),
    ]
